/*
 * This source file was generated by the Gradle 'init' task
 */
package hm222yj.quicksort;

import java.util.Random;
import hm222yj.quicksort.quicksort.Quicksort;
import hm222yj.quicksort.filemanager.FileManager;

public class App {
    public static void main(String[] args) {
        // DATA SETTINGS
        int dataSize = 10;
        int minValue = 0;
        int maxValue = 10;

        App app = new App();
        Quicksort quicksort = new Quicksort();

        int[] arrayToSort = app.randomArray(dataSize, minValue, maxValue);
        // for (int number : arrayToSort) {
        //     System.out.println(number);
        // }
        
        System.out.println("-----------------------------SOOOOOORTING-------------------------------");

        quicksort.sortArray(arrayToSort, minValue, maxValue-1);
        // for (int number : arrayToSort) {
        //     System.out.println(number);
        // }

    }


    // Random array generator
    private int[] randomArray(int dataSize, int minValue, int maxValue) {
        Random randomNumber = new Random();
        int[] arrayData = new int[dataSize];
        for (int i = 0; i < dataSize; i++) {
            arrayData[i] = randomNumber.nextInt(maxValue - minValue + 1) + minValue;
        }
        return arrayData;
    }
}
